version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: application
    ports:
      - 5432:5432
    volumes:
      - ~/docker-postgresql:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: postgres_panel
    ports:
      - 8280:8080
